syntax on
set tabstop=4
set autoindent

noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

colorscheme yowish
set ttimeoutlen=0
set noshowmode
set showcmd
set number relativenumber
highlight LineNR ctermfg=darkgray
set tabstop=4 shiftwidth=4 expandtab

call plug#begin()
Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase' }
call plug#end()

let g:Hexokinase_highlighters = [ 'backgroundfull' ]

set termguicolors

let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
