#! /bin/sh

bspc rule -r *:*

killall sxhkd; sxhkd -c ~/.config/sxhkd/bspwm ~/.config/sxhkd/sxhkdrc &
$HOME/.config/polybar/launch.sh

# bspc monitor HDMI-A-0 -d 1 3 4 5 6 7 8 9
# bspc monitor HDMI-A-1 -d 2
bspc monitor ^1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor ^2 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_struts	 false
bspc config top_padding			 30

bspc rule -a Origin.exe floating=on
bspc rule -a origin.exe floating=on

bspc rule -a Screenkey manage=off
bspc rule -a Polybar layer=above

