#! /bin/sh

killall sxhkd; sxhkd -c ~/.config/sxhkd/bspwm ~/.config/sxhkd/sxhkdrc &

# bspc monitor HDMI-A-0 -d 1 3 4 5 6 7 8 9
# bspc monitor HDMI-A-1 -d 2
bspc monitor ^1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor ^2 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
